### ISSUE TITLE
Evil::Client::Dictionary will not support keyword arguments?

### ISSUE THREAD

**Issue by NaturalHokke** [evilmartians/evil-client#32]
```yaml
---
# config.yml
- name: "A"
  code: 65
- name: "B"
  code: 66
```

```ruby
class Codepoint < Evil::Client::Model
  extend  Evil::Client::Dictionary["config.yml"]

  option :name
  option :code
end

Codepoint.all
# => `new': wrong number of arguments (given 1, expected 0)
```
